FROM rockylinux/rockylinux:9.3
EXPOSE 22
EXPOSE 2222
EXPOSE 3306
EXPOSE 5432
RUN dnf install -y sudo iputils less passwd openssh-clients openssh-server vim nano python39
COPY id_ed25519.pub  /root/.ssh/authorized_keys
COPY node.sh /entrypoint.sh
RUN rm -rf /run/nologin
ENTRYPOINT ["/entrypoint.sh"]
